apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      run: app1
  replicas: 2
  template:
    metadata:
      labels:
        run: app1
    spec:

    
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node1



      containers:
        - name: app1
          image: muntaseri/bs-app1:v1
          ports:
            - containerPort: 8000
              protocol: TCP
       configMap:
          name: app1-configmap
          items: 
            - key: app1.html
              path: app1.html

